# Generated by Django 2.2.3 on 2019-09-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_googlesync'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesync',
            name='is_dir',
            field=models.BooleanField(default=False),
        ),
    ]
