# Generated by Django 3.1.2 on 2020-12-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20201212_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlephotossync',
            name='last_sync',
            field=models.DateTimeField(null=True),
        ),
    ]
