# Generated by Django 2.2.3 on 2019-10-16 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_auto_20190919_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDrive_Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdrive_id', models.CharField(default='', max_length=256)),
                ('parent_gdrive_id', models.CharField(default='', max_length=256)),
                ('path', models.CharField(max_length=256)),
                ('is_dirty', models.BooleanField(default=False)),
                ('is_dir', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Google_Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_token', models.CharField(default='', max_length=256)),
                ('g_refresh_token', models.CharField(default='', max_length=256)),
                ('gdrive_changes_token', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='clouduser',
            name='g_refresh_token',
        ),
        migrations.RemoveField(
            model_name='clouduser',
            name='g_token',
        ),
        migrations.DeleteModel(
            name='GoogleSync',
        ),
        migrations.AddField(
            model_name='google_tokens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gdrive_index',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
