# Generated by Django 2.2.6 on 2019-10-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_auto_20191016_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google_tokens',
            name='g_refresh_token',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='google_tokens',
            name='g_token',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='google_tokens',
            name='gdrive_changes_token',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
